services:
  nginx:
    image: heat-pump-app-frontend-nginx:1.0
    container_name: "nginx"
    depends_on:
        - backend
    ports:
        # host:container
        - "8000:80"
    restart: always

  backend:
    image: heat-pump-app-backend:1.0
    container_name: "backend"
    expose:
      # expose port 8000 to other containers
      - 8000
    devices:  # allow the backend container to use the host USB port
    # (for the modbus adapter)
      # host:container
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
